# Generated by Django 4.1 on 2022-08-13 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=30, verbose_name='用户账号')),
                ('id_password', models.CharField(max_length=255, verbose_name='用户密码')),
                ('user_name', models.CharField(max_length=30, verbose_name='用户名称')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=50, null=True, verbose_name='职位')),
                ('role_id', models.IntegerField(verbose_name='角色id')),
                ('user_status', models.IntegerField(default=1, verbose_name='用户状态')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
    ]
