# Generated by Django 4.1 on 2022-08-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(null=True, verbose_name='角色id'),
        ),
    ]
