# Generated by Django 4.1 on 2022-08-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_manage', '0002_alter_user_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_value', models.IntegerField(verbose_name='角色值')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, verbose_name='角色标识')),
                ('enable', models.IntegerField(verbose_name='是否启用')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('details', models.CharField(max_length=255, null=True, verbose_name='详情')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'sys_role',
            },
        ),
    ]
