# Generated by Django 4.1 on 2022-08-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_manage', '0004_alter_role_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_des',
            field=models.CharField(max_length=30, null=True, verbose_name='角色描述'),
        ),
    ]
