# Generated by Django 4.1 on 2022-08-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_manage', '0005_user_role_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='权限名称')),
                ('type', models.IntegerField(verbose_name='权限类型')),
                ('code', models.CharField(max_length=30, null=True, verbose_name='权限标识')),
                ('url', models.CharField(max_length=30, null=True, verbose_name='权限路径')),
                ('open_type', models.CharField(max_length=20, null=True, verbose_name='权限类型-中文')),
                ('parent_id', models.IntegerField(null=True, verbose_name='父类编号')),
                ('icon', models.CharField(max_length=50, null=True, verbose_name='图标')),
                ('sort', models.IntegerField(null=True, verbose_name='排序')),
                ('enable', models.IntegerField(default=1, verbose_name='是否开启')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'sys_power',
            },
        ),
        migrations.CreateModel(
            name='RolePower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(verbose_name='角色id')),
                ('power_id', models.IntegerField(verbose_name='权限id')),
                ('power_type', models.IntegerField(verbose_name='类型')),
            ],
            options={
                'db_table': 'role_power',
            },
        ),
    ]
