# Generated by Django 4.1 on 2022-08-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='菜单名称')),
                ('desc', models.CharField(max_length=50, null=True, verbose_name='菜单描述')),
                ('type', models.IntegerField(null=True, verbose_name='菜单类型')),
                ('url', models.CharField(max_length=50, null=True, verbose_name='菜单url')),
                ('parent_id', models.IntegerField(null=True, verbose_name='父级id')),
                ('icon', models.CharField(max_length=50, null=True, verbose_name='图标')),
                ('sort', models.IntegerField(null=True, verbose_name='排序')),
            ],
            options={
                'db_table': 'web_logo',
            },
        ),
    ]
